package com.crossvale.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ClusterOutput implements java.io.Serializable {

        static final long serialVersionUID = 1L;

        @org.kie.api.definition.type.Label(value = "cluster")
        private java.util.List<com.crossvale.model.ClusterOut> cluster;

        public ClusterOutput() {
        }

        public java.util.List<com.crossvale.model.ClusterOut> getCluster() {
                return this.cluster;
        }

        public void setCluster(
                        java.util.List<com.crossvale.model.ClusterOut> cluster) {
                this.cluster = cluster;
        }

        public ClusterOutput(
                        java.util.List<com.crossvale.model.ClusterOut> cluster) {
                this.cluster = cluster;
        }

}
