package com.crossvale.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ClusterOut implements java.io.Serializable {

        static final long serialVersionUID = 1L;

        @org.kie.api.definition.type.Label("name")
        private java.lang.String name;

        @org.kie.api.definition.type.Label(value = "fleet")
        private java.util.List<com.crossvale.model.FleetOut> fleet;

        @org.kie.api.definition.type.Label(value = "cloud")
        private java.lang.String cloud;

        public ClusterOut() {
        }

        public java.lang.String getName() {
                return this.name;
        }

        public void setName(java.lang.String name) {
                this.name = name;
        }

        public java.util.List<com.crossvale.model.FleetOut> getFleet() {
                return this.fleet;
        }

        public void setFleet(
                        java.util.List<com.crossvale.model.FleetOut> fleet) {
                this.fleet = fleet;
        }

        public java.lang.String getCloud() {
                return this.cloud;
        }

        public void setCloud(java.lang.String cloud) {
                this.cloud = cloud;
        }

        public ClusterOut(java.lang.String name,
                        java.util.List<com.crossvale.model.FleetOut> fleet,
                        java.lang.String cloud) {
                this.name = name;
                this.fleet = fleet;
                this.cloud = cloud;
        }

}

