package com.crossvale.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ClusterInput implements java.io.Serializable {

        static final long serialVersionUID = 1L;

        @org.kie.api.definition.type.Label(value = "cluster")
        private java.util.List<com.crossvale.model.Cluster> cluster;

        public ClusterInput() {
        }

        public java.util.List<com.crossvale.model.Cluster> getCluster() {
                return this.cluster;
        }

        public void setCluster(
                        java.util.List<com.crossvale.model.Cluster> cluster) {
                this.cluster = cluster;
        }

        public ClusterInput(
                        java.util.List<com.crossvale.model.Cluster> cluster) {
                this.cluster = cluster;
        }

}

