package com.crossvale.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Fleet implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("currentCapactiy")
	private java.lang.Integer currentCapacity;
	@org.kie.api.definition.type.Label("name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("availabilityZone")
	private java.lang.String availabilityZone;

	@org.kie.api.definition.type.Label("instanceType")
	private java.lang.String instanceType;
	@org.kie.api.definition.type.Label("cpuLoad")
	private String cpuLoad;
	@org.kie.api.definition.type.Label("memoryLoad")
	private java.lang.String memoryLoad;
	@org.kie.api.definition.type.Label("networkLoad")
	private java.lang.String networkLoad;
	
	@org.kie.api.definition.type.Label("price")
	private java.util.List<com.crossvale.model.Price> price;

	@org.kie.api.definition.type.Label(value = "id")
	private java.lang.String id;

	public Fleet() {
	}

	public java.lang.Integer getCurrentCapacity() {
		return this.currentCapacity;
	}

	public void setCurrentCapacity(java.lang.Integer currentCapacity) {
		this.currentCapacity = currentCapacity;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getAvailabilityZone() {
		return this.availabilityZone;
	}

	public void setAvailabilityZone(java.lang.String availabilityZone) {
		this.availabilityZone = availabilityZone;
	}

	public java.lang.String getInstanceType() {
		return this.instanceType;
	}

	public void setInstanceType(java.lang.String instanceType) {
		this.instanceType = instanceType;
	}

	public java.lang.String getMemoryLoad() {
		return this.memoryLoad;
	}

	public void setMemoryLoad(java.lang.String memoryLoad) {
		this.memoryLoad = memoryLoad;
	}

	public java.lang.String getNetworkLoad() {
		return this.networkLoad;
	}

	public void setNetworkLoad(java.lang.String networkLoad) {
		this.networkLoad = networkLoad;
	}

	public java.lang.String getCpuLoad() {
		return this.cpuLoad;
	}

	public void setCpuLoad(java.lang.String cpuLoad) {
		this.cpuLoad = cpuLoad;
	}

	public java.lang.String getId() {
		return this.id;
	}
	
	public java.util.List<com.crossvale.model.Price> getPrice() {
		return this.price;
	}

	public void setPrice(java.util.List<com.crossvale.model.Price> price) {
		this.price = price;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public Fleet(java.lang.Integer currentCapacity, java.lang.String name, java.lang.String availabilityZone,
			java.lang.String instanceType, java.util.List<com.crossvale.model.Price> price, java.lang.String cpuLoad,
			java.lang.String memoryLoad, java.lang.String networkLoad, java.lang.String id) {
		this.currentCapacity = currentCapacity;
		this.name = name;
		this.availabilityZone = availabilityZone;
		this.instanceType = instanceType;
		this.price = price;
		this.cpuLoad = cpuLoad;
		this.memoryLoad = memoryLoad;
		this.networkLoad = networkLoad;
		this.id = id;
	}

}
