package rules

import com.crossvale.model.FleetOut;
import org.joda.time.DateTime;

function boolean isBetween(int start, int end ){
	DateTime dt = new DateTime();
    int hhmm = dt.getHourOfDay()*100 + dt.getMinuteOfDay();
    System.out.println("Hour of Day: " + hhmm);
    return start <= hhmm && hhmm < end;
}

rule "FleetA 0-1200"
	when 
		fleetObject: FleetOut(name.equals("fleetA") && isBetween(0, 1200))
	then
		fleetObject.setTargetCapacity(15);
		System.out.println("Firing rule: " + drools.getRule().getName());
	end
rule "FleetA 1200-2400"
	when 
		fleetObject: FleetOut(name.equals("fleetA") && isBetween(1200, 2400))
	then
		fleetObject.setTargetCapacity(25);
		System.out.println("Firing rule: " + drools.getRule().getName());
	end